### ISSUE TITLE
Bufferframe is shallow copy, may lead to error [heap-use-after-free]

### ISSUE THREAD

**Issue by SYaoJun** [zz-jason/leanstore#102]
mBf point to a space which allocate by mBuffer, if out the scope， the mBuffer member will invoke its destructor function, and the mBf is invalid. 

![205673f719958c42e70987123595ddb9](https://github.com/user-attachments/assets/24b95db1-2a9d-4b3c-b9d7-f990037444c3)

![54a300c387fec055e5ee33da5c38f95a](https://github.com/user-attachments/assets/5cc8f826-1221-41af-b359-2bbdb39a8864)
## core reason
this is a shallow copy, the mBf rely on input argument bf's life cycle.  
![eafe2423ac8272b99083935eb9ff0fe3](https://github.com/user-attachments/assets/1d937d03-2aa3-46a3-8307-b42abf89e4fd)
## reproduce
in debug_tsan mode, call this variable is function will triger this error [heap-use-after-free]
![a79b7ab80b306ce370b3fdf67a66a67d](https://github.com/user-attachments/assets/b438542c-af18-47bd-a8c9-a81958b63f78)

## some ideas
1. use std::unique_ptr move the ownership to member variable mBf
2. deep copy in Reset()

**Comment by SYaoJun** [comment]
https://github.com/zz-jason/leanstore/actions/runs/10232967819/job/28310732700  reproduce this bug

**Comment by zz-jason** [comment]
Currently, the only usage of AsyncWriteBuffer is page evictor, refer to `src/buffer-manager/AsyncWriteBuffer.cpp`.

The shadow copy buffer frame address avoids unnecessary memory copy and additional memory consumption. These buffer frames are further given back to the user of AsyncWriteBuffer. The principles are:

1. BufferFrames are owned by the caller, not AsyncWriteBuffer.
2. The caller must guarantee these buffer frames stay valid until `IterateFlushedBfs()` is called.

So:
1. The easiest way to solve this issue is to change the test implementation. 
2. We do need some debug checks to ensure these referenced buffer frames are valid. But buffer frames are never reclaimed once they are created since the leanstore daemon is initialized, this issue may never happen.
